# Site settings
# NB! Set your site's url, otherwise nothing will work
#url: "https://WilderDan.github.io/personal-site"
google-tracking-id: false

#############
# HTML Head #
#############
lang: "en"
author: "Dan Wilder"
title: "Dan Wilder"
description: "Blog and website of Dan Wilder. Focused on my projects and studies."
keywords: "Wilder, Dan, personal, projects, studies"
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "<figure class='quote'>
        <blockquote>
          All we have to decide is what to do with the time that is given us.
        </blockquote>
        <figcaption>
          Gandalf, <cite>The Fellowship of the Ring</cite>
        </figcaption>
      </figure>"
  - text: "<figure class='quote'>
        <blockquote>
          Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.
        </blockquote>
        <figcaption>
          Michael Scott, <cite>The Office</cite>
        </figcaption>
      </figure>"
  - text: "<figure class='quote'>
        <blockquote>
          Live as if you were to die tomorrow. Learn as if you were to live forever.
        </blockquote>
        <figcaption>
          Mahatma Gandhi
        </figcaption>
      </figure>"
#me-img: "/img/gh-profile.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/WilderDan.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True
disqus-shortname: "personal-jekyll-theme"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "your@email.here"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "Dan Wilder" 
#author_blurb_image: "/img/author.png"
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/WilderDan"
#  - icon: "linkedin-in"
#    url: "https://www.linkedin.com"
#  - icon: "x-twitter"
#    url: "https://twitter.com/"
#  - icon: "rss"
#    url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
#  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
